name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Including node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install node modules
        run: npm i
      - name: Building the webpage
        run: npm run build
      - name: Printing the list of files
        run: ls
      - name: Deploy to 'public' banch
        run: |
          git config --local user.email deejayadipl@gmail.com
          git config --local user.name deejayadi
          git checkout -b public
          git add -f build/
          git commit -m "Deploy React app to 'public' branch"
          git push origin public
